apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es5cluster
  namespace: civil-connect
spec:
  serviceName: "es5cluster"
  replicas: 3
  template:
    metadata:
      labels:
        app: es5cluster
    spec:
      containers:
      - name: es5node
        image: giorgiocasciaro/alpine-es5-cluster:0.0.1
        command: ["sh"]
        args: ["-c", "cp /es5cluster-config-dir/elasticsearch.yml /opt/elasticsearch/config/elasticsearch.yml; /opt/elasticsearch/bin/elasticsearch"]
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms50m -Xmx50m"
        ports:
        - containerPort: 9200
          name: elasticsearch
        - containerPort: 9300
          name: elasticsearch2
        volumeMounts:
        - name: es5cluster-volume
          mountPath: /var/data/elasticsearch
        - name: es5cluster-config-dir
          mountPath: /es5cluster-config-dir/
      volumes:
      - name: es5cluster-volume
        hostPath:
          path: /es5clusterNodeData
      - name: es5cluster-config-dir
        configMap:
          name: es5cluster-config-dir
