version: '3'

services:
   aerospike:
     image: aerospike/aerospike-server

     expose:
        - "3000"
        - "3001"
        - "3002"
        - "3003"
     ports:
        - "3000:3000"
        - "3001:3001"
        - "3002:3002"
        - "3003:3003"
     entrypoint: sh -c " /usr/bin/asd --fgdaemon --config-file /opt/aerospike/etc/aerospike.conf"
    #  entrypoint: bash
     volumes:
       - ./aerospike.conf:/opt/aerospike/etc/aerospike.conf
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.10

   smtp:
     image: digiplant/fake-smtp
     # ports:
     #   - "1025:25"
     volumes:
       - ./email:/var/email

   aerospike-tools:
     stdin_open: true
     tty: true
     image: aerospike/aerospike-tools
     networks:
       civilmicroservices:
          # aliases:
          #  - aerospike-tools

   aerospike-amc:
     image: mrbar42/aerospike-amc
     expose:
        - "9001"
        - "8081"
     ports:
        - "8081:8081"
        - "9001:9001"
    #  entrypoint: /opt/elasticsearch/bin/elasticsearch
    #  volumes:
    #    - ./aerospike.conf:/etc/aerospike/aerospike.conf
     networks:
       civilmicroservices:
          # aliases:
          #  - aerospike-amc


   elasticsearch:
      image: itzg/elasticsearch:latest
      ports:
        - "9200:9200"
        - "9300:9300"
      # tty : true
    #  image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    #  ports:
    #     - "9200:9200"
    #     - "9300:9300"
      # environment:
      #  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    #    transport.host: 127.0.0.1
    #    http.host: 0.0.0.0
    #   #  xpack.security.enabled: "false"
    #   #  xpack.monitoring.enabled: "false"
    #   #  xpack.graph.enabled: "false"
    #   #  xpack.watcher.enabled: "false"
      networks:
       civilmicroservices:
          ipv4_address: 172.16.100.11

   test:
     image: giorgiocasciaro/alpine-node-lua-aerospike:v1
     #entrypoint: sh -c "ifconfig -a && node /service/service/tests/base.test"
     entrypoint: sh -c "cd /service/ && npm start"
     #entrypoint: sh -c "cd /service/ && npm run watch_test"
    #  ports:
    #    - "9229"
     environment:
       netHost: 172.16.100.12
       serviceName: test
       elasticsearchHost: 172.16.100.11:9200
       aerospikeHosts: 172.16.100.10:3000
     volumes:
        - ../sharedSchema/:/sharedSchema/
        - ./test/service:/service/service
        - ./test/node_modules_compiled:/service/node_modules
        - ./test/package.json:/service/package.json
        - ../jesus/:/service/node_modules/sint-bit-jesus/
        - ../schemaManager/:/service/node_modules/sint-bit-schema-manager/
        # - ../cqrs/:/service/node_modules/sint-bit-cqrs/
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.12

   test-remote:
     image: giorgiocasciaro/alpine-node-lua-aerospike:v1
     #entrypoint: bash
     entrypoint: sh -c "cd /service/ && npm run watch_test_remote"
    #  ports:
    #    - "9229"
     environment:
       serviceName: testRemote
       netHost: 172.16.100.13
       elasticsearchHost: 172.16.100.11:9200
       aerospikeHosts: 172.16.100.10:3000
     volumes:
        - ../sharedSchema/:/sharedSchema/
        - ./test/service:/service/service
        - ./test/node_modules_compiled:/service/node_modules
        - ./test/package.json:/service/package.json
        - ../jesus/:/service/node_modules/sint-bit-jesus/
        - ../schemaManager/:/service/node_modules/sint-bit-schema-manager/
        - ../cqrs/:/service/node_modules/sint-bit-cqrs/
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.13

   www:
     image: nginx:1.12.0-alpine
     entrypoint: sh -c "nginx -g 'daemon off;'"
     ports:
       - "10080:10080"
     volumes:
        - ./email:/usr/share/nginx/html/email
        - ./www/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./www/civilconnect/static:/usr/share/nginx/html/civilconnect
        # - ./www/admin:/usr/share/nginx/html/admin
        - ./www/admin_simple:/usr/share/nginx/html/admin_simple
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.14

   users:
     image: giorgiocasciaro/alpine-node-lua-aerospike:v1
    #  entrypoint: sh -c "cd /service/ && npm run watch_test"
     entrypoint: sh -c "cd /service/ && npm start"
    #  ports:
      #  - "9229"
     environment:
       serviceName: users
       smtpHost: smtp:25
       netHost: 172.16.100.15
       netCors: http://172.16.100.14:80,http://172.16.100.14,http://localhost:8080,http://127.0.0.1:8080
       elasticsearchHost: 172.16.100.11:9200
       aerospikeHosts: aerospike:3000
     volumes:
        - ../sharedSchema/:/sharedSchema/
        - ./users/service:/service/service
        - ./users/node_modules_compiled:/service/node_modules
        - ./users/package.json:/service/package.json
        - ../jesus/:/service/node_modules/sint-bit-jesus/
        - ../schemaManager/:/service/node_modules/sint-bit-schema-manager/
        - ../cqrs/:/service/node_modules/sint-bit-cqrs/
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.15

   admin:
     image: giorgiocasciaro/alpine-node-lua-aerospike:v1
    #  entrypoint: sh -c "cd /service/ && npm run watch_test_remote"
     entrypoint: sh -c "cd /service/ && npm start"
    #  ports:
      #  - "10080"
      #  - "9229"
     environment:
       serviceName: admin
       netHost: 172.16.100.16
       netCors: http://172.16.100.14:80,http://172.16.100.14,http://localhost:8080,http://127.0.0.1:8080
       elasticsearchHost: 172.16.100.11:9200
       aerospikeHosts: 172.16.100.10:3000
     volumes:
        - ../sharedSchema/:/sharedSchema/
        - ./admin/service:/service/service
        - ./admin/node_modules_compiled:/service/node_modules
        - ./admin/package.json:/service/package.json
        - ../jesus/:/service/node_modules/sint-bit-jesus/
        - ../schemaManager/:/service/node_modules/sint-bit-schema-manager/
        - ../cqrs/:/service/node_modules/sint-bit-cqrs/
     networks:
       civilmicroservices:
          ipv4_address: 172.16.100.16

networks:
  civilmicroservices:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.100.0/24
