# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.cpus = 2
    # Customize the amount of memory on the VM:
    vb.memory = "2024"
  end

  config.vm.network "private_network", ip: "192.168.33.103"
  config.vm.hostname = "kube-node-03"
  config.vm.provision "shell", path: "install.sh"

  # config.vm.define "node1" do |node1|
  #   config.vm.network "private_network", ip: "192.168.33.101"
  #   config.vm.hostname = "kube-node-01"
  #   config.vm.provision "shell", path: "node1_install.sh"
  # end

  # config.vm.define "node2" do |node2|
  #   # config.vm.network "private_network", ip: "192.168.33.102"
  #   # config.vm.hostname = "kube-node-02"
  #   config.vm.provision "shell", path: "node2_install.sh"
  # end
  #
  # config.vm.define "node3" do |node3|
  #   # config.vm.network "private_network", ip: "192.168.33.103"
  #   # config.vm.hostname = "kube-node-03"
  #   config.vm.provision "shell", path: "node3_install.sh"
  # end
end
