version:                   '3'

services:
  app:
    working_dir:           /service
    image:                 giorgiocasciaro/ubuntu-node:v1
   #  entrypoint:          sh -c "cd /service/ && npm run watch_test_remote"
    command:               -c "sleep 20 && npm run start"

    environment:
      netHost:             app
      schemaHost:          'http://schema:10000'
      aerospikeHosts:      aerospike:3000
      netCors:             http://localhost:82,http://127.0.0.1:82,http://localhost:8080,http://127.0.0.1:8080,http://localhost:10080,http://127.0.0.1:10080
      NODE_ENV:            development
    volumes:
       - ../app:/service
       - ../../NPM/jesus:/service/node_modules/sint-bit-jesus
       - ../../NPM/cqrs:/service/node_modules/sint-bit-cqrs
    # depends_on:
    #   - aerospike
    ports:
      - 82:10070
      - 83:10080
    networks:
      - microservicesNet
      - aerospike

networks:
  microservicesNet:
    driver:                bridge
  aerospike:
    driver:                bridge
