apiVersion: v1
kind: Service
metadata:
  name: civil-microservices-smtp
  namespace: civil-connect
spec:
  ports:
  - port: 25
    name: smtp
  clusterIP: None
  selector:
    app: civil-microservices-smtp
