apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: civil-microservices-smtp
  namespace: civil-connect
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: civil-microservices-smtp
    spec:
      containers:
        - name: users
          image: namshi/smtp
          envFrom:
            - configMapRef:
                name: civil-microservices-smtp
