version: '3'

services:
   www:
     image: giorgiocasciaro/civil-microservices-www:v0
     command: bash -c "echo "$$NGINX_CONF" > /etc/nginx/nginx.conf ;  nginx -g 'daemon off;' "
     environment:
       NGINX_CONF: |-
          events {
              worker_connections  1024;
          }
          http {
            client_max_body_size 500M;
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;
            resolver 127.0.0.11;
            server {
                listen 80 ;
                location / {
                    root /usr/share/nginx/html;
                }
            }
          }
     networks:
       - microservicesNet
     build:
      context: ./
      # dockerfile: Dockerfile
     ports:
      - 80:80
     deploy:
      # placement:
      #   constraints: [node.role == manager]
      mode: global
      # replicas: 3


networks:
  microservicesNet:
    driver: overlay
