apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: civil-microservices-logger
  namespace: civil-connect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: civil-microservices-logger
    spec:
      containers:
        - name: users
          image: 'giorgiocasciaro/civil-microservices-logger:version-0'
          envFrom:
            - configMapRef:
                name: civil-microservices-logger
