apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: civil-connect
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:alpine
        command: ["elasticsearch"]
        # args: ["-c", "/etc/nginx-config-dir/nginx.conf"]
        ports:
        - containerPort: 9200
        # - containerPort: 9200
        # - containerPort: 5044
      #   volumeMounts:
      #     - name: elasticsearch
      #       mountPath: /var/lib/elasticsearch
      #       subPath: elasticsearch
      # volumes:
      # - name: elasticsearch
      #   persistentVolumeClaim:
      #     claimName: elasticsearch
