version: '3'

services:
   aerospike:
     image: giorgiocasciaro/civil-microservices-aerospike:latest
     command: bash -c "echo \"$$AEROSPIKE_CONF\" > /etc/aerospike/aerospike.conf ; cat /etc/aerospike/aerospike.conf ; asd --foreground "
     networks:
       - aerospike
     environment:
       AEROSPIKE_CONF: |-
          service {
          		node-id-interface eth0
          }

          logging {
          	console {
          		context any info
          	}
          }

          network {
          	service {
          		address eth0
          		port 3000
          		access-address eth0 virtual

          	}
            heartbeat {
               mode multicast
               multicast-group 239.0.0.1
               port 3002
             }

          	fabric {
          		port 3001
          	}

          	info {
          		port 3003
          	}
          }

          namespace civilconnect {
          	replication-factor 1
          	memory-size 500M

          	storage-engine device {
          		file /opt/aerospike/data/civilconnect.dat
          		filesize 500M
          	}
          }
     deploy:
      # placement:
      #   constraints: [node.role == manager]
      #mode: global
      replicas: 3


networks:
  aerospike:
    driver: bridge
