
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.synced_folder_opts = {
     owner: "_apt"
   }
  end
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.synced_folder "token/", "/token"
  config.vm.synced_folder "script/", "/script"
  config.vm.synced_folder "../", "/civil"

  config.vm.define "node1", primary: true do |node1|
      # db.vm.box = "mysql"
      node1.vm.network "public_network", ip: "192.168.1.211", bridge: "enp2s0"
      node1.vm.hostname = "node1"
      node1.vm.provision "shell", inline: "
        sh /script/install.sh
        sudo docker swarm init --advertise-addr 192.168.1.211
        sudo docker swarm join-token -q  worker > /token/worker.tkn
        sudo docker swarm join-token -q  manager > /token/manager.tkn
      "

  end


  config.vm.define "node2" do |node2|
      # db.vm.box = "mysql"
      node2.vm.network "public_network", ip: "192.168.1.212", bridge: "enp2s0"
      node2.vm.hostname = "node2"
      node2.vm.provision "shell", inline: "
        sh /script/install.sh
        sudo docker swarm join 192.168.1.211 --advertise-addr 192.168.1.212 --token $(cat /token/manager.tkn)
      "
  end


  config.vm.define "node3" do |node3|
      # db.vm.box = "mysql"
      node3.vm.network "public_network", ip: "192.168.1.213", bridge: "enp2s0"
      node3.vm.hostname = "node3"
      node3.vm.provision "shell", inline: "
        sh /script/install.sh
        sudo docker swarm join 192.168.1.211 --advertise-addr 192.168.1.213 --token $(cat /token/manager.tkn)
      "
  end

end
