apiVersion: v1
kind: Pod
metadata:
  name: civil-microservices-test
  namespace: civil-connect
spec:
  containers:
  - image: giorgiocasciaro/civil-microservices-test:v1
    # command:
    #   - sleep
    #   - "3600"
    # imagePullPolicy: IfNotPresent
    name: civil-microservices-test
    env:
      - name: aerospikeHosts
        value: "10.42.0.31:3000"
  # restartPolicy: Always
