apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  namespace: civil-connect
  labels:
    name: echo-server
spec:
  containers:
  - image: jmalloc/echo-server
    imagePullPolicy: IfNotPresent
    name: echo-server
    #command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx-config-dir/nginx.conf"]
    # args: ["-c", "/etc/nginx-config-dir/nginx.conf"]
    ports:
    - containerPort: 8080
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  echo-server
  namespace: civil-connect
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    name: echo-server
