apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: external-grafana
  name: external-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000
  selector:
    k8s-app: grafana
