
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2024"
  end

  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
  # config.ssh.insert_key = 'true'

  config.vm.network "private_network", ip: "192.168.33.100"
  config.vm.hostname = "kube-master"
  config.vm.provision "shell", path: "install.sh"

end
