version: '3'

services:
   www:
     image: giorgiocasciaro/civil-microservices-users
     command: bash -c "cd /service/ && npm run watch_start"
     environment:
       uploadPath: /uploads/
       schemaHost: 'http://schema:10000'
       confirmEmailUrl: http://localhost:8080/#/registration/ConfirmEmail/
       serviceName: users
       netHost: 172.16.100.15
       netHostHttpPublicPort: 10080
       netCors: http://172.16.100.14:80,http://172.16.100.14,http://localhost:8080,http://127.0.0.1:8080,http://localhost:10080,http://127.0.0.1:10080
       elasticsearchHost: elasticsearch:9200
       aerospikeHosts: aerospike:3000
       NODE_ENV: development
       sendEmails: 'true'
       smtpConfigJson: '{ "host": "smtp", "port": 1025, "secure": false }'

     volumes:
        - ./FS/:/uploads/
        - ./service:/service/service
        - ./node_modules_compiled:/service/node_modules
        - ./package.json:/service/package.json
        - ../NPM/jesus/:/service/node_modules/sint-bit-jesus/
        - ../NPM/cqrs/:/service/node_modules/sint-bit-cqrs/

     networks:
       - microservicesNet
     build:
      context: ./
      # dockerfile: Dockerfile
     ports:
      - 80:80



networks:
  microservicesNet:
    driver: bridge
