FROM giorgiocasciaro/alpine-node-compiler:v2
# RUN apk add --update --repository http://nl.alpinelinux.org/alpine/edge/main libwebp-dev fftw-dev  && \
#   apk add --update \
#   --repository http://dl-3.alpinelinux.org/alpine/edge/testing \
#   libwebp-dev fftw-dev vips-dev \
#   && rm -rf /var/cache/apk/*
# ENTRYPOINT ["bash"]
