apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-dir
  namespace: civil-connect
data:
  nginx.conf: |
    server {
        listen              443 ssl;
        server_name         backend1.example.com;
        ssl_certificate     /etc/nginx/server.crt;
        ssl_certificate_key /etc/nginx/server.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location /test {
            proxy_pass external-grafana.kube-system:3000;
        }
    }
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDzTCCArWgAwIBAgIJAPuhwcAVYxWfMA0GCSqGSIb3DQEBCwUAMH0xCzAJBgNV
    BAYTAklUMQ4wDAYDVQQIDAVpdGFseTEOMAwGA1UEBwwFbGVjY2UxDTALBgNVBAoM
    BHNpbnQxFDASBgNVBAMMC2Npdmljb25uZWN0MSkwJwYJKoZIhvcNAQkBFhpnaW9y
    Z2lvLmNhc2NpYXJvQGdtYWlsLmNvbTAeFw0xNjEyMTUyMjQ5MDJaFw0xNzEyMTUy
    MjQ5MDJaMH0xCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVpdGFseTEOMAwGA1UEBwwF
    bGVjY2UxDTALBgNVBAoMBHNpbnQxFDASBgNVBAMMC2Npdmljb25uZWN0MSkwJwYJ
    KoZIhvcNAQkBFhpnaW9yZ2lvLmNhc2NpYXJvQGdtYWlsLmNvbTCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAK3J/Eb+tlPI+5AghnyyGQhvrbvt/d0FKefZ
    piHpXT2axWOPvVyVk0WenTMZjI6K12KUBEqVA0YzTDa/70pG5ox+/0WU5R6YANOt
    mO8ZhFkdw4o2xMO9eFELRmKs60cLcvbidEnJClh9IyCH37YN7e2edNSEmtr7Lw1j
    WJJJTNtedUdpy0g8c9HC27Tz8TdxTHrV8zgISPXiudghLwPWuVjE03XRUDWcHEq0
    gB/MGOxWV8a+/kvFSpe4RKUazkfXtMcKviHybC7BDe3tOMdRhAZTNjwtvb6+YfoY
    UDI8S4+ZfK/cq69G+qR8ZnkqELmLqt9B9VjXDTiYSwQ0wEP5dqMCAwEAAaNQME4w
    HQYDVR0OBBYEFFuwGY77Gb8+V5oX7yKoxhH3X4WzMB8GA1UdIwQYMBaAFFuwGY77
    Gb8+V5oX7yKoxhH3X4WzMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
    AJqqAHYpKg8KWi+QmYdNTS9QaS4EsmjTGmhMRW3vFy/0rbvbtKs8Whkj+syvM/m0
    qSupAS0HRFiO6EeAvHgeGKGWtSW7dYJYXcxUeIapsPUSIzYrGkhuxa1fw8QJl52f
    HBl98KjlouPCG1RRGc46LPomVV0TWfbn7wTE4Sb0BF9xSjC1tcuvgtSVTFj27hup
    5WwH31pdIL0bBVl6PkhAQ2lw5dCO5cxNkSJUsmbHAvIwNDuFrCp/Ys1eaNyIRB2K
    MWPbmMOjIWc6chxlQ0JtqvU/7JKu8AUfEiTju9qqOTK9RPOEO0z09jRfvXYOy7PY
    p+D6Sy3Q+5iEfR7Q6entSb0=
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtyfxG/rZTyPuQ
    IIZ8shkIb6277f3dBSnn2aYh6V09msVjj71clZNFnp0zGYyOitdilARKlQNGM0w2
    v+9KRuaMfv9FlOUemADTrZjvGYRZHcOKNsTDvXhRC0ZirOtHC3L24nRJyQpYfSMg
    h9+2De3tnnTUhJra+y8NY1iSSUzbXnVHactIPHPRwtu08/E3cUx61fM4CEj14rnY
    IS8D1rlYxNN10VA1nBxKtIAfzBjsVlfGvv5LxUqXuESlGs5H17THCr4h8mwuwQ3t
    7TjHUYQGUzY8Lb2+vmH6GFAyPEuPmXyv3KuvRvqkfGZ5KhC5i6rfQfVY1w04mEsE
    NMBD+XajAgMBAAECggEAc3td7VtCkwhhydMjKuc55TY4z0GFSQIuZ4dkcvJcaBxZ
    gCA657PpCgEtWpBmqy2tlC7hbyH37AUYZuVBwCy+9KtLO9SGL784BXE8x90/6evy
    TPy54Ywc0FXarqVTLoF4IoA2X/V8r3JwDiTbzmERMq3x2mpHcK4rBQ14BLU6oiXY
    2bjYGpxmDmZaXUQopvpntNOCaZaEx4w6fozPNvCQVX9abggY369jn11SSPNaqdUi
    k/NuZQoj01mGbBDfjR7NUbB/oB3oyYArr9/Aej6yFcNQSN/psrPNvGiSefvOcVku
    Eq9ucWDZAcl+bVG9InWIwDnnc7DSOKVrW1KYWSvswQKBgQDcMX9rE7FxxbxLFK2j
    M8Sn42FOrWVMJcYg+BfmiM+FN0ZBb5rYZEQMGjYoSl5jkNfYI3td3FZ7OhSjAls7
    6JGfFhonH3m9yP+b4j7pGcJBO+z0s1EB/MhMQg0KL2OMLzNBvWFnSFgcqjWxgHru
    dzQRejnkEHohm1d5q7WuVGvhAwKBgQDKDLSwZu4USHce6PPZMP8tk1DiAAGEOmrT
    v70Ehv94zWe9LnWV2hnwKMaFRbz5u/jinMq9kmmLMlGlbIGagglpKv6tu2jkb38Y
    MAZSNKmlstAUTgkbO0oLQQoHJlVHm8AP4e/G7A9v73r+jYrzCtoI2eiaJZQjFJfr
    JEvP4ZKR4QKBgCecx/1tZ4i+N+eR6sLnd0N0xnau/wA583DO8Q3KIvsmPH9dIpA3
    SX6b4I5TArQKxKnfiDwUfYJhqoDA1cTrS/dAtKfBI9eep01V4FdzCN1PeIt1Due6
    oBYH8+yXJeN8Qk5bUYCRJTjS7iHmqTbpPva99FgxFqehGJWM7HxWN6odAoGBAMfC
    TBpjiVqwUmVS91NyJ7fNgBgQ3W73uopjdOM2/PlYSwo1FrfzC9Xu2mcFDdLyTxzs
    210VlheyxhoA7xntGpTJl0X4lbnTqhol0PoRavCRmzuX81TjB0+dG+b5tTK4/+gz
    /rXyyUhnwnhNRGUKA4rgtiFAqfcM8y3dkr6STDDBAoGBAIr6+Y1g0v4WQqadQn0H
    eGe02cqC1kkQC4YUkuynTwiYLtLUrrdJz/H/8G1FPA/7IRnuDNkjHNRRF0WDFxck
    RUZ+9AJBs8qyCkCxBxF5s8x7jrVq+pGHtM78L5rYxJv5m3IHaSqaZB06oZ+u7ZYB
    zhNT6/jExj7Xax9joUjA+Yg8
    -----END PRIVATE KEY-----
