
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.synced_folder_opts = {
     owner: "_apt"
   }
  end
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  # config.ssh.username = 'root'
  # config.ssh.password = 'vagrant'
  # config.ssh.insert_key = 'true'

  config.vm.network "public_network", ip: "192.168.1.201", bridge: "enp2s0"
  config.vm.hostname = "node1"
  config.vm.provision "shell", path: "install.sh"

end
