version:                '3'

services:
   users:
     image:             giorgiocasciaro/ubuntu-node:v1
     working_dir:       /service
     command:           -c "sleep 60 && npm run start "
     environment:
       uploadPath:      /uploads/
       schemaHost:      'http://schema:10000'
       confirmEmailUrl: http://localhost:8080/#/registration/ConfirmEmail/
       serviceName:     users
       netHost:         users
      #  netHostHttpPublicPort: 10080
      #  netCors:       http://172.16.100.14:80,http://172.16.100.14,http://localhost:8080,http://127.0.0.1:8080,http://localhost:10080,http://127.0.0.1:10080
      #  elasticsearchHost: elasticsearch:9200
       aerospikeHosts:  aerospike:3000
       NODE_ENV:        development
       sendEmails:      'true'
       smtpConfigJson: '{ "host": "smtp", "port": 1025, "secure": false }'
     volumes:
        - ../users:/service
        - ../../FS/:/uploads/
        - ../../NPM/jesus/:/service/node_modules/sint-bit-jesus/
        - ../../NPM/cqrs/:/service/node_modules/sint-bit-cqrs/

     depends_on:
       - aerospike
     networks:
       - microservicesNet
       - aerospike

networks:
  microservicesNet:
    driver:             bridge
  aerospike:
    driver:             bridge
