version: '3'

services:
   aerospike:
     image: giorgiocasciaro/miniaerospike:0.0.2
     command: bash -c "cp  /config/test.conf /etc/aerospike/aerospike.conf ; asd --foreground"
     networks:
       - aerospike
     build:
      context: ./docker
      dockerfile: Dockerfile
     deploy:
      # placement:
      #   constraints: [node.role == manager]
      #mode: global
      replicas: 3


networks:
  aerospike:
    # driver: overlay
