apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: civil-connect
  labels:
    name: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  selector:
    name: elasticsearch
